// 直接按需导入各个图标
export {
  ArrowDownRight,
  ArrowUpRight,
  Box,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardPaste,
  CodeXml,
  Copy,
  Crop,
  FlipHorizontal2,
  FlipVertical2,
  Hand,
  ImageDown,
  ImagePlay,
  ImagePlus,
  LayoutGrid,
  ListCollapse,
  Maximize,
  MessageCirclePlus,
  Moon,
  MoveDownLeft,
  Pencil,
  Pipette,
  Redo,
  RotateCcw,
  Settings2,
  Slash,
  Smile,
  Square,
  Sun,
  Sunset,
  Trash2,
  Type,
  Undo,
  ZoomIn,
  ZoomOut,
} from 'lucide-vue-next'

// 向后兼容的默认导出
// 使用 * as 语法重新导出所有图标
import * as Icons from 'lucide-vue-next'

// 只导出项目中实际使用的图标
export default {
  Camera: Icons.Camera,
  Check: Icons.Check,
  Square: Icons.Square,
  Circle: Icons.Circle,
  Slash: Icons.Slash,
  MoveDownLeft: Icons.MoveDownLeft,
  Pencil: Icons.Pencil,
  Smile: Icons.Smile,
  Undo: Icons.Undo,
  Redo: Icons.Redo,
  ChevronRight: Icons.ChevronRight,
  ChevronDown: Icons.ChevronDown,
  ChevronUp: Icons.ChevronUp,
  RotateCcw: Icons.RotateCcw,
  ZoomIn: Icons.ZoomIn,
  ZoomOut: Icons.ZoomOut,
  Hand: Icons.Hand,
  Crop: Icons.Crop,
  FlipHorizontal2: Icons.FlipHorizontal2,
  FlipVertical2: Icons.FlipVertical2,
  Sunset: Icons.Sunset,
  Box: Icons.Box,
  LayoutGrid: Icons.LayoutGrid,
  ImagePlus: Icons.ImagePlus,
  Type: Icons.Type,
  CodeXml: Icons.CodeXml,
  ClipboardPaste: Icons.ClipboardPaste,
  ImagePlay: Icons.ImagePlay,
  Maximize: Icons.Maximize,
  ListCollapse: Icons.ListCollapse,
  ArrowUpRight: Icons.ArrowUpRight,
  ArrowDownRight: Icons.ArrowDownRight,
  ImageDown: Icons.ImageDown,
  Copy: Icons.Copy,
  Settings2: Icons.Settings2,
  ChevronLeft: Icons.ChevronLeft,
  Pipette: Icons.Pipette,
  Trash2: Icons.Trash2,
  Sun: Icons.Sun,
  Moon: Icons.Moon,
  MessageCirclePlus: Icons.MessageCirclePlus,
}
